#!/bin/bash

cd src

# Static Linking

gcc \
-Wall \
-flto \
-Os \
-Wl,-dead_strip,-dead_strip_dylibs \
-ffast-math \
-fno-stack-protector \
-fomit-frame-pointer \
-ffunction-sections \
-fvisibility=hidden \
-fno-rtti \
-fdata-sections \
main.c \
scenecontroller.c \
scenes/mainscene.c \
scenes/infoscene.c \
scenes/gamescene.c \
-o breakout.out \
-framework CoreFoundation \
-framework CoreGraphics \
-framework CoreAudio \
-framework CoreServices \
-framework ApplicationServices \
-framework IOKit \
-framework AppKit \
-framework AudioToolbox \
-framework OpenAL \
-framework OpenGL \
`pkg-config --libs --cflags \
allegro_font-static-5 \
allegro_ttf-static-5 \
allegro_image-static-5 \
allegro_primitives-static-5 \
allegro_audio-static-5 \
allegro_acodec-static-5 \
allegro_main-static-5 \
allegro-static-5` \
`pkg-config --libs freetype2 vorbis vorbisfile ogg flac opus opusfile --cflags --static`

strip breakout.out
cp breakout.out ../breakout
cp breakout.out ../release/Breakout.app/Contents/MacOS/breakout